ALTER TYPE "UserRole" RENAME VALUE 'ADMIN' TO 'ADMINISTRADOR';
ALTER TYPE "UserRole" RENAME VALUE 'USUARIO' TO 'VISITANTE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'VENDEDOR';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'VISITANTE_AVANZADO';
