export const AUDIT_ACTIONS = {
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_CREATED: "USER_CREATED",
  USER_UPDATED: "USER_UPDATED",
  USER_ACTIVATED: "USER_ACTIVATED",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  FILE_UPLOADED: "FILE_UPLOADED",
  CATALOG_CREATED: "CATALOG_CREATED",
  CATALOG_UPDATED: "CATALOG_UPDATED",
  CATALOG_DELETED: "CATALOG_DELETED",
  IMPORT_PUBLISHED: "IMPORT_PUBLISHED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ENTITY_TYPES = {
  USER: "User",
  STORAGE_FILE: "StorageFile",
  CATALOG: "Catalog",
  IMPORT: "Import",
} as const;

export type AuditEntityType =
  (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES];
