import type {
  ImportActionType,
  ImportJobStatus,
  ImportSheetClassification,
  Prisma,
  ProductImageStatus,
} from "@/generated/prisma/client";
import ExcelJS from "exceljs";
import { requireAdmin } from "@/server/auth";
import {
  buildExistingCodeIndex,
  buildExistingContentIndex,
  detectSemanticFlags,
  isImageCodeHeader,
  mapSheetToProducts,
  parseWorkbookFromBuffer,
  resolveImportProductMatchId,
  toExcelJsBuffer,
  type ImportJobConfig,
  type MappedProductRow,
  type ParsedSheet,
  type DetectedHeader,
} from "@/server/importers";
import { findRepeatedColumnNames } from "@/server/importers/repeated-column.detector";
import {
  GENERATED_PRIMARY_CODE_COLUMN_KEY,
  GENERATED_PRIMARY_CODE_DISPLAY_NAME,
} from "@/server/importers/generated-primary-code";
import { extractImagesFromZip, ZipExtractionError } from "@/server/image-processors/zip-extractor";
import { columnRepository } from "@/server/repositories/column.repository";
import { importJobRepository } from "@/server/repositories/import-job.repository";
import { productImageRepository } from "@/server/repositories/product-image.repository";
import { productRepository } from "@/server/repositories/product.repository";
import { uploadedFileRepository } from "@/server/repositories/uploaded-file.repository";
import { catalogRepository } from "@/server/repositories/catalog.repository";
import { folderRepository } from "@/server/repositories/folder.repository";
import { buildIndexedTextForMappedProduct } from "@/server/services/product-field.builder";
import { normalizeIndexedText } from "@/server/search/search-normalizer";
import { prisma } from "@/server/database/prisma";
import {
  buildStoragePath,
  downloadFile,
  uploadFile,
} from "@/server/storage";
import { STORAGE_BUCKETS } from "@/server/storage/types";
import { StorageError } from "@/server/storage/errors";
import { imageExtractionService } from "./image-extraction.service";
import { productImageService } from "./product-image.service";
import { equivalenceService } from "./equivalence.service";
import { AUDIT_ACTIONS, AUDIT_ENTITY_TYPES } from "./audit.constants";
import { auditService } from "./audit.service";
import { priceImportService } from "./price-import.service";
import type { MappedPriceItemRow } from "@/server/importers/price-item-row.mapper";
import { ImportError } from "./import.errors";
import { uploadedFileRetentionService } from "./uploaded-file-retention";

const BATCH_SIZE = 500;

function isAutoGeneratedColumnName(name: string): boolean {
  return /^columna \d+$/i.test(name.trim());
}

const TERMINAL_STATUSES: ImportJobStatus[] = [
  "PUBLISHED",
  "FAILED",
  "CANCELLED",
];

type ImportJobProgress = {
  phase?: string;
  percent?: number;
  message?: string;
};

function readImportProgress(progress: unknown): ImportJobProgress {
  if (typeof progress === "object" && progress !== null) {
    return progress as ImportJobProgress;
  }

  return {};
}

function isImageProcessingResume(job: {
  status: ImportJobStatus;
  progress: unknown;
}): boolean {
  const progress = readImportProgress(job.progress);
  return job.status === "PROCESSING" && progress.phase === "images";
}

function assertCanConfigureImport(job: {
  status: ImportJobStatus;
  progress: unknown;
}): void {
  const progress = readImportProgress(job.progress);
  const allowed =
    job.status === "PENDING_CONFIG" ||
    job.status === "READY_TO_APPLY" ||
    (job.status === "PROCESSING" && progress.phase === "preview");

  if (!allowed) {
    throw new ImportError(
      `Estado de importación inválido: ${job.status}.`,
      "INVALID_STATE",
    );
  }
}

function previewGenerationRestoreStatus(
  previousStatus: ImportJobStatus,
): ImportJobStatus {
  if (previousStatus === "READY_TO_APPLY") {
    return "READY_TO_APPLY";
  }

  return "PENDING_CONFIG";
}

function toPrismaJsonValue<T>(value: T): Prisma.InputJsonValue {
  return JSON.parse(JSON.stringify(value)) as Prisma.InputJsonValue;
}

function formatPreviewError(error: unknown): string {
  const base = "No se pudo generar la vista previa.";

  if (!(error instanceof Error) || !error.message) {
    return base;
  }

  const message = error.message.replace(/\s+/g, " ").trim();

  if (message.includes("Unknown argument")) {
    return `${base} Error de configuración de columnas en base de datos. Reinicie el servidor de desarrollo y ejecute «pnpm db:generate».`;
  }

  if (message.length <= 220) {
    return `${base} ${message}`;
  }

  return base;
}

export type UploadImportFileInput = {
  buffer: Buffer;
  originalFilename: string;
  contentType: string;
};

export type UploadImportImageInput = {
  buffer: Buffer;
  originalFilename: string;
  contentType: string;
  isZip: boolean;
};

export type SetImportDestinationInput =
  | {
      destinationType?: "CATALOG_FOLDER";
      catalogId: string;
      folderId: string;
      sheetName: string;
    }
  | {
      destinationType: "PRICE_LIST";
      priceListId: string;
      sheetName: string;
      supplierName: string;
      supplierDate: string;
    };

export type SetImportConfigInput = ImportJobConfig & {
  expectedPriceListId?: string;
  expectedFolderId?: string;
};

export type ApplyImportInput = {
  actionType: ImportActionType;
  confirmed: boolean;
};

export type ImportProgress = {
  phase: string;
  percent: number;
  message: string;
};

export type ImportReport = {
  fileName: string;
  catalogName: string | null;
  folderName: string | null;
  sheetImported: string | null;
  sheetsDetected: number;
  productsProcessed: number;
  productsCreated: number;
  productsSkipped: number;
  productsMatched: number;
  formulasDetected: number;
  formulasWithoutCachedValue: number;
  imagesDetected: number;
  imagesExtracted: number;
  imagesAssociated: number;
  imagesPendingReview: number;
  imagesRejected: number;
  imagesAmbiguous: number;
  embeddedImagesDetected: number;
  embeddedImagesAssociated: number;
  embeddedImagesPendingReview: number;
  embeddedImagesRejected: number;
  rowsWithEmbeddedImages: number;
  productsWithEmbeddedImages: number;
  productsWithMultipleEmbeddedImages: number;
  columnsDetected: number;
  columnsCreated: number;
  errors: string[];
  warnings: string[];
  actionApplied: ImportActionType | null;
};

function assertStatus(current: ImportJobStatus, allowed: ImportJobStatus[]): void {
  if (!allowed.includes(current)) {
    throw new ImportError(
      `Estado de importación inválido: ${current}.`,
      "INVALID_STATE",
    );
  }
}

function toClassification(
  classification: ParsedSheet["classification"],
): ImportSheetClassification {
  return classification;
}

function countFormulas(products: MappedProductRow[]): {
  formulasDetected: number;
  formulasWithoutCachedValue: number;
} {
  let formulasDetected = 0;
  let formulasWithoutCachedValue = 0;

  for (const product of products) {
    for (const formula of product.formulas) {
      formulasDetected += 1;
      if (!formula.hasCachedValue) {
        formulasWithoutCachedValue += 1;
      }
    }
  }

  return { formulasDetected, formulasWithoutCachedValue };
}

export class CatalogImportService {
  async uploadAndCreateJob(input: UploadImportFileInput) {
    const { profile: admin } = await requireAdmin();

    let uploaded;
    try {
      uploaded = await uploadFile({
        bucket: STORAGE_BUCKETS.EXCEL_ORIGINALS,
        path: buildStoragePath("imports", input.originalFilename),
        body: input.buffer,
        contentType: input.contentType,
        originalFilename: input.originalFilename,
        auditContext: { userId: admin.id },
      });
    } catch (error) {
      if (error instanceof StorageError) {
        throw new ImportError(error.message, "INVALID_FILE");
      }
      throw error;
    }

    const uploadedFile = await uploadedFileRepository.create({
      originalName: input.originalFilename,
      storagePath: uploaded.path,
      mimeType: uploaded.contentType,
      sizeBytes: uploaded.sizeBytes,
      uploadedById: admin.id,
    });

    const job = await importJobRepository.create({
      uploadedFileId: uploadedFile.id,
      status: "STORED",
    });

    return { jobId: job.id, uploadedFileId: uploadedFile.id };
  }

  async createJobFromUploadedFile(uploadedFileId: string) {
    await requireAdmin();

    const file = await uploadedFileRepository.findById(uploadedFileId);
    if (!file) {
      throw new ImportError("Archivo no encontrado.", "IMPORT_NOT_FOUND");
    }

    const active = await importJobRepository.findActiveByUploadedFileId(uploadedFileId);
    if (active) {
      throw new ImportError(
        "Hay una importación en curso para este archivo.",
        "INVALID_STATE",
      );
    }

    const job = await importJobRepository.create({
      uploadedFileId,
      status: "STORED",
    });

    return { jobId: job.id, uploadedFileId };
  }

  async getJob(jobId: string) {
    await requireAdmin();
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    return job;
  }

  async analyzeJob(jobId: string) {
    await requireAdmin();
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    assertStatus(job.status, ["STORED", "PENDING_DESTINATION"]);

    await importJobRepository.update(jobId, {
      status: "ANALYZING",
      progress: { phase: "analyze", percent: 10, message: "Analizando archivo..." },
      errorMessage: null,
    });

    try {
      const buffer = await downloadFile(
        STORAGE_BUCKETS.EXCEL_ORIGINALS,
        job.uploadedFile.storagePath,
      );
      const workbook = await parseWorkbookFromBuffer(buffer);

      await importJobRepository.replaceSheets(
        jobId,
        workbook.sheets.map((sheet) => ({
          importJobId: jobId,
          sheetName: sheet.sheetName,
          classification: toClassification(sheet.classification),
          rowCount: sheet.rowCount,
          columnCount: sheet.columnCount,
          detectedHeaders: sheet.headers,
          metadata: {
            classificationReason: sheet.classificationReason,
            headerRow: sheet.headerRow,
            imageCount: sheet.imageCount,
            embeddedImageSummary: sheet.embeddedImageSummary,
          },
        })),
      );

      await uploadedFileRepository.updateStatus(job.uploadedFileId, "PROCESSED");

      return importJobRepository.update(jobId, {
        status: "PENDING_DESTINATION",
        progress: {
          phase: "destination",
          percent: 40,
          message: "Seleccione catálogo, carpeta y hoja destino.",
        },
      });
    } catch (error) {
      console.error("[catalogImportService.analyzeJob]", error);
      const clientMessage = "Error al analizar el archivo.";

      await importJobRepository.update(jobId, {
        status: "FAILED",
        errorMessage: clientMessage,
        finishedAt: new Date(),
        progress: { phase: "failed", percent: 100, message: clientMessage },
      });

      await uploadedFileRepository.updateStatus(job.uploadedFileId, "FAILED");
      await uploadedFileRetentionService.purgeIfWithoutRetainedImport(job.uploadedFileId);
      throw new ImportError(clientMessage, "ANALYSIS_FAILED");
    }
  }

  async setDestination(jobId: string, input: SetImportDestinationInput) {
    await requireAdmin();
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    assertStatus(job.status, ["PENDING_DESTINATION", "PENDING_CONFIG", "READY_TO_APPLY"]);

    const sheet = job.sheets.find((item) => item.sheetName === input.sheetName);
    if (!sheet) {
      throw new ImportError("Hoja no encontrada en el archivo.", "VALIDATION_ERROR");
    }

    if (sheet.classification !== "IMPORTABLE") {
      throw new ImportError(
        "La hoja seleccionada no es importable.",
        "SHEET_NOT_IMPORTABLE",
      );
    }

    if (input.destinationType === "PRICE_LIST") {
      return priceImportService.setDestination(jobId, {
        priceListId: input.priceListId,
        sheetName: input.sheetName,
        supplierName: input.supplierName,
        supplierDate: input.supplierDate,
      });
    }

    const folder = await folderRepository.findById(input.folderId);
    if (!folder || folder.catalogId !== input.catalogId) {
      throw new ImportError("Carpeta destino inválida.", "VALIDATION_ERROR");
    }

    const catalog = await catalogRepository.findById(input.catalogId);
    if (!catalog) {
      throw new ImportError("Catálogo destino inválido.", "VALIDATION_ERROR");
    }

    await importJobRepository.deletePreview(jobId);

    return importJobRepository.update(jobId, {
      destinationType: "CATALOG_FOLDER",
      catalogId: input.catalogId,
      folderId: input.folderId,
      priceListId: null,
      targetSheetName: input.sheetName,
      status: "PENDING_CONFIG",
      progress: {
        phase: "config",
        percent: 55,
        message: "Configure columnas y genere la vista previa.",
      },
    });
  }

  async setConfig(jobId: string, input: SetImportConfigInput) {
    await requireAdmin();
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    assertCanConfigureImport(job);
    this.assertImportDestinationMatches(job, input);

    const previousStatus = job.status;
    const existingConfig = (job.config as ImportJobConfig | null) ?? {};
    const config: ImportJobConfig = {
      ...existingConfig,
      columnMapping: input.columnMapping,
      primaryCodeColumnKey: input.useGeneratedPrimaryCodes
        ? undefined
        : input.primaryCodeColumnKey,
      descriptionColumnKey: input.descriptionColumnKey,
      useGeneratedPrimaryCodes: input.useGeneratedPrimaryCodes ?? false,
    };

    await importJobRepository.update(jobId, {
      config,
      progress: {
        phase: "preview",
        percent: 70,
        message: "Generando vista previa...",
      },
    });

    try {
      return await this.buildPreview(jobId, config);
    } catch (error) {
      console.error("[catalogImportService.setConfig]", error);

      await importJobRepository.update(jobId, {
        status: previewGenerationRestoreStatus(previousStatus),
        progress: {
          phase: "config",
          percent: 55,
          message: "Configure columnas y genere la vista previa.",
        },
      });

      if (error instanceof ImportError) {
        throw error;
      }

      throw new ImportError(formatPreviewError(error), "PREVIEW_FAILED");
    }
  }

  private async loadWorkbookFromJob(
    job: NonNullable<Awaited<ReturnType<typeof importJobRepository.findByIdWithRelations>>>,
  ): Promise<ExcelJS.Workbook> {
    const buffer = await downloadFile(
      STORAGE_BUCKETS.EXCEL_ORIGINALS,
      job.uploadedFile.storagePath,
    );
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(toExcelJsBuffer(buffer));
    return workbook;
  }

  private async buildRowToProductMap(
    folderId: string,
    mappedProducts: MappedProductRow[],
    options: {
      preferContentMatch?: boolean;
      matchKeys?: readonly string[];
    } = {},
  ): Promise<Map<number, string>> {
    const products = await productRepository.findForMatchingByFolder(folderId);
    const codeIndex = buildExistingCodeIndex(products);
    const contentIndex = buildExistingContentIndex(products, {
      allowedKeys: options.matchKeys,
    });
    const map = new Map<number, string>();

    for (const row of mappedProducts) {
      const productId = resolveImportProductMatchId(
        row,
        { codeIndex, contentIndex },
        {
          allowedKeys: options.matchKeys,
          preferContentMatch: options.preferContentMatch,
        },
      );
      if (productId) {
        map.set(row.rowNumber, productId);
      }
    }

    return map;
  }

  private async processImportImages(input: {
    jobId: string;
    folderId: string;
    sheet: ParsedSheet;
    mappedProducts: MappedProductRow[];
    config: ImportJobConfig;
    columns: Awaited<ReturnType<typeof columnRepository.findByFolderIdOrdered>>;
    workbook: ExcelJS.Workbook;
    /** Skip embedded images on rows not mapped to a product (COMBINAR). */
    skipUnmatchedEmbeddedRows?: boolean;
  }): Promise<{
    warnings: string[];
    stats: {
      extracted: number;
      associated: number;
      pendingReview: number;
      rejected: number;
      ambiguous: number;
    };
    embedded: {
      extracted: number;
      associated: number;
      pendingReview: number;
      rejected: number;
      rowsWithEmbeddedImages: number;
      productsWithEmbeddedImages: number;
      productsWithMultipleEmbeddedImages: number;
    };
  }> {
    const warnings: string[] = [];
    const stats = {
      extracted: 0,
      associated: 0,
      pendingReview: 0,
      rejected: 0,
      ambiguous: 0,
    };
    const embedded = {
      extracted: 0,
      associated: 0,
      pendingReview: 0,
      rejected: 0,
      rowsWithEmbeddedImages: 0,
      productsWithEmbeddedImages: 0,
      productsWithMultipleEmbeddedImages: 0,
    };

    const preferContentMatch = Boolean(input.config.useGeneratedPrimaryCodes);
    const matchKeys = input.columns
      .filter((column) => column.internalKey !== GENERATED_PRIMARY_CODE_COLUMN_KEY)
      .map((column) => column.internalKey);
    const rowToProductId = await this.buildRowToProductMap(
      input.folderId,
      input.mappedProducts,
      { preferContentMatch, matchKeys },
    );

    if (input.sheet.imageCount > 0) {
      const embeddedResult = await imageExtractionService.processEmbeddedImages({
        workbook: input.workbook,
        sheet: input.sheet,
        folderId: input.folderId,
        importJobId: input.jobId,
        rowToProductId,
        // Without ZIP, never send embedded pictures to the ZIP-style review step
        // for rows that were not part of this apply batch (e.g. COMBINAR matches).
        skipUnmatchedRows: preferContentMatch || Boolean(input.skipUnmatchedEmbeddedRows),
        folderColumns: input.columns.map((column) => ({
          internalKey: column.internalKey,
          originalName: column.originalName,
          displayName: column.displayName,
        })),
      });

      warnings.push(...embeddedResult.warnings);
      stats.extracted += embeddedResult.stats.extracted;
      stats.associated += embeddedResult.stats.associated;
      stats.pendingReview += embeddedResult.stats.pendingReview;
      stats.rejected += embeddedResult.stats.rejected;
      stats.ambiguous += embeddedResult.stats.ambiguous;
      embedded.extracted = embeddedResult.stats.extracted;
      embedded.associated = embeddedResult.stats.associated;
      embedded.pendingReview = embeddedResult.stats.pendingReview;
      embedded.rejected = embeddedResult.stats.rejected;
      embedded.rowsWithEmbeddedImages = embeddedResult.stats.rowsWithEmbeddedImages;
      embedded.productsWithEmbeddedImages = embeddedResult.stats.productsWithEmbeddedImages;
      embedded.productsWithMultipleEmbeddedImages =
        embeddedResult.stats.productsWithMultipleEmbeddedImages;
    }

    const externalImages = input.config.externalImages ?? [];
    if (externalImages.length > 0) {
      const existingExternalCount = await productImageRepository.countByImportJobSources(
        input.jobId,
        ["EXTERNAL_ZIP", "EXTERNAL_UPLOAD"],
      );

      if (existingExternalCount === 0) {
        const imageInputs = await Promise.all(
          externalImages.map(async (ref) => ({
            buffer: await downloadFile(STORAGE_BUCKETS.TEMP_IMPORTS, ref.storagePath),
            originalName: ref.originalName,
            mimeType: ref.mimeType,
            source: ref.source,
          })),
        );

        const imageCodeColumnKeys = input.columns
          .filter(
            (column) => column.isImageCode || isImageCodeHeader(column.originalName),
          )
          .map((column) => column.internalKey);

        const external = await productImageService.processExternalImages({
          importJobId: input.jobId,
          folderId: input.folderId,
          images: imageInputs,
          imageCodeColumnKeys,
          includePrimaryCodeInMatch: !input.config.useGeneratedPrimaryCodes,
        });

        warnings.push(...external.warnings);
        stats.extracted += external.stats.processed;
        stats.associated += external.stats.associated;
        stats.pendingReview += external.stats.pendingReview;
        stats.rejected += external.stats.rejected;
        stats.ambiguous += external.stats.ambiguous;
      }
    }

    return { warnings, stats, embedded };
  }

  async uploadImportImages(jobId: string, files: UploadImportImageInput[]) {
    await requireAdmin();
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    assertStatus(job.status, [
      "STORED",
      "PENDING_DESTINATION",
      "PENDING_CONFIG",
      "READY_TO_APPLY",
    ]);

    const config = (job.config as ImportJobConfig | null) ?? {};
    const externalImages = [...(config.externalImages ?? [])];

    for (const file of files) {
      if (file.isZip) {
        let extracted;
        try {
          extracted = await extractImagesFromZip(file.buffer);
        } catch (error) {
          if (error instanceof ZipExtractionError) {
            throw new ImportError(error.message, "INVALID_FILE");
          }
          throw error;
        }

        for (const entry of extracted) {
          const staged = await productImageService.uploadExternalToStaging({
            jobId,
            buffer: entry.buffer,
            originalFilename: entry.originalName,
            contentType: "application/octet-stream",
            source: "EXTERNAL_ZIP",
          });
          externalImages.push(staged);
        }
        continue;
      }

      const staged = await productImageService.uploadExternalToStaging({
        jobId,
        buffer: file.buffer,
        originalFilename: file.originalFilename,
        contentType: file.contentType,
        source: "EXTERNAL_UPLOAD",
      });
      externalImages.push(staged);
    }

    return importJobRepository.update(jobId, {
      config: {
        ...config,
        externalImages,
      } as unknown as Prisma.InputJsonValue,
    });
  }

  async completeImageReview(jobId: string) {
    const { profile: admin } = await requireAdmin();
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    assertStatus(job.status, ["PENDING_REVIEW"]);

    const updated = await importJobRepository.update(jobId, {
      status: "PUBLISHED",
      finishedAt: new Date(),
      progress: {
        phase: "published",
        percent: 100,
        message: "Revisión de imágenes completada. Importación publicada.",
      },
    });

    auditService.logOperationSafe({
      userId: admin.id,
      action: AUDIT_ACTIONS.IMPORT_PUBLISHED,
      entityType: AUDIT_ENTITY_TYPES.IMPORT,
      entityId: jobId,
    });

    return updated;
  }

  private async loadTargetSheet(job: NonNullable<Awaited<ReturnType<typeof importJobRepository.findByIdWithRelations>>>) {
    if (!job.targetSheetName) {
      throw new ImportError("Debe seleccionar una hoja destino.", "VALIDATION_ERROR");
    }

    const buffer = await downloadFile(
      STORAGE_BUCKETS.EXCEL_ORIGINALS,
      job.uploadedFile.storagePath,
    );
    const workbook = await parseWorkbookFromBuffer(buffer);
    const sheet = workbook.sheets.find((item) => item.sheetName === job.targetSheetName);

    if (!sheet) {
      throw new ImportError("Hoja destino no encontrada.", "VALIDATION_ERROR");
    }

    return sheet;
  }

  private async pruneOrphanAutoGeneratedColumns(
    folderId: string,
    sheet: ParsedSheet,
  ): Promise<void> {
    const columns = await columnRepository.findByFolderIdOrdered(folderId);
    const sheetOriginalNames = new Set(
      sheet.headers.map((header) => header.originalName.trim().toLowerCase()),
    );
    const sheetInternalKeys = new Set(
      sheet.headers.map((header) => header.internalKey),
    );

    for (const column of columns) {
      if (!isAutoGeneratedColumnName(column.originalName)) {
        continue;
      }

      if (column.isPrimaryCode || column.isDescription) {
        continue;
      }

      if (sheetOriginalNames.has(column.originalName.trim().toLowerCase())) {
        continue;
      }

      if (sheetInternalKeys.has(column.internalKey)) {
        continue;
      }

      const hasData = await productRepository.hasNonEmptyDynamicValue(
        folderId,
        column.internalKey,
      );

      if (!hasData) {
        await columnRepository.delete(column.id);
      }
    }
  }

  private assertImportDestinationMatches(
    job: NonNullable<Awaited<ReturnType<typeof importJobRepository.findByIdWithRelations>>>,
    input: SetImportConfigInput,
  ): void {
    if (job.destinationType === "PRICE_LIST") {
      if (!input.expectedPriceListId) {
        throw new ImportError(
          "Debe confirmar la lista de precios destino.",
          "VALIDATION_ERROR",
        );
      }

      if (job.priceListId !== input.expectedPriceListId) {
        throw new ImportError(
          "La lista de precios destino no coincide. Volvé al paso Destino y confirmá de nuevo.",
          "VALIDATION_ERROR",
        );
      }

      return;
    }

    if (!input.expectedFolderId) {
      throw new ImportError("Debe confirmar la carpeta destino.", "VALIDATION_ERROR");
    }

    if (job.folderId !== input.expectedFolderId) {
      throw new ImportError(
        "La carpeta destino no coincide. Volvé al paso Destino y confirmá de nuevo.",
        "VALIDATION_ERROR",
      );
    }
  }

  private resolveMappedFolderColumnKey(
    header: DetectedHeader,
    columns: Awaited<ReturnType<typeof columnRepository.findByFolderIdOrdered>>,
    config: ImportJobConfig,
  ): string | null {
    const mapping = new Map(
      (config.columnMapping ?? []).map((entry) => [
        entry.headerInternalKey,
        entry.folderColumnInternalKey,
      ]),
    );

    const mapped = mapping.get(header.internalKey);
    if (mapped === "__ignore__") {
      return null;
    }

    if (mapped) {
      return mapped;
    }

    const byName = columns.find(
      (column) =>
        column.originalName.trim().toLowerCase() ===
        header.originalName.trim().toLowerCase(),
    );

    return byName?.internalKey ?? header.internalKey;
  }

  private async syncColumnsFromSheet(
    folderId: string,
    sheet: ParsedSheet,
    config: ImportJobConfig,
    options: { persist: boolean; replaceSchema?: boolean } = { persist: true },
  ) {
    if (options.persist && options.replaceSchema) {
      await columnRepository.deleteByFolder(folderId);
    }

    let columns = await columnRepository.findByFolderIdOrdered(folderId);
    const activeHeaders = sheet.headers.filter((header) => {
      return this.resolveMappedFolderColumnKey(header, columns, config) !== null;
    });

    if (columns.length === 0) {
      const semanticUsed = { primary: false, description: false };
      const columnsToCreate = [];

      for (let index = 0; index < activeHeaders.length; index += 1) {
        const header = activeHeaders[index];
        const targetKey = this.resolveMappedFolderColumnKey(header, columns, config);
        if (!targetKey) {
          continue;
        }

        const flags = detectSemanticFlags(header.originalName);
        const isPrimaryCode = config.useGeneratedPrimaryCodes
          ? false
          : config.primaryCodeColumnKey
            ? config.primaryCodeColumnKey === targetKey
            : !semanticUsed.primary && flags.isPrimaryCode;
        const isDescription = config.descriptionColumnKey
          ? config.descriptionColumnKey === targetKey
          : !semanticUsed.description && flags.isDescription;

        if (isPrimaryCode) semanticUsed.primary = true;
        if (isDescription) semanticUsed.description = true;

        columnsToCreate.push({
          folderId,
          originalName: header.originalName,
          displayName: header.originalName,
          internalKey: targetKey,
          dataType: header.inferredDataType,
          order: index,
          isPrimaryCode,
          isDescription,
          // Image-code columns are only for ZIP filename matching.
          isImageCode: config.useGeneratedPrimaryCodes ? false : flags.isImageCode,
          isSearchable: isPrimaryCode || isDescription,
          isFilterable: false,
        });
      }

      if (columnsToCreate.length > 0) {
        if (options.persist) {
          await columnRepository.createMany(columnsToCreate);
          columns = await columnRepository.findByFolderIdOrdered(folderId);
        } else {
          columns = [
            ...columns,
            ...columnsToCreate.map((column) => this.toPreviewFolderColumn(column)),
          ];
        }
      }

      if (config.useGeneratedPrimaryCodes) {
        columns = await this.syncGeneratedPrimaryCodeColumn(folderId, columns, options.persist);
        columns = await this.clearImageCodeFlagsWithoutZip(
          folderId,
          columns,
          options.persist,
        );
      }

      return columns;
    }

    const existingKeys = new Set(columns.map((column) => column.internalKey));
    const existingNames = new Set(
      columns.map((column) => column.originalName.trim().toLowerCase()),
    );
    const columnsToCreate = [];

    for (let index = 0; index < activeHeaders.length; index += 1) {
      const header = activeHeaders[index];
      const targetKey = this.resolveMappedFolderColumnKey(header, columns, config);
      if (!targetKey) {
        continue;
      }

      if (existingKeys.has(targetKey)) {
        continue;
      }

      if (existingNames.has(header.originalName.trim().toLowerCase())) {
        continue;
      }

      const flags = detectSemanticFlags(header.originalName);
      columnsToCreate.push({
        folderId,
        originalName: header.originalName,
        displayName: header.originalName,
        internalKey: targetKey,
        dataType: header.inferredDataType,
        order: columns.length + index,
        isPrimaryCode:
          !config.useGeneratedPrimaryCodes && config.primaryCodeColumnKey === targetKey,
        isDescription: config.descriptionColumnKey === targetKey,
        isImageCode: config.useGeneratedPrimaryCodes ? false : flags.isImageCode,
        isSearchable:
          (!config.useGeneratedPrimaryCodes &&
            config.primaryCodeColumnKey === targetKey) ||
          config.descriptionColumnKey === targetKey,
        isFilterable: false,
      });
    }

    if (columnsToCreate.length > 0) {
      if (options.persist) {
        await columnRepository.createMany(columnsToCreate);
        columns = await columnRepository.findByFolderIdOrdered(folderId);
      } else {
        columns = [
          ...columns,
          ...columnsToCreate.map((column) => this.toPreviewFolderColumn(column)),
        ];
      }
    }

    if (config.primaryCodeColumnKey || config.descriptionColumnKey) {
      for (const column of columns) {
        const nextPrimary =
          !config.useGeneratedPrimaryCodes &&
          column.internalKey === config.primaryCodeColumnKey;
        const nextDescription = column.internalKey === config.descriptionColumnKey;

        if (
          column.isPrimaryCode !== nextPrimary ||
          column.isDescription !== nextDescription
        ) {
          if (options.persist) {
            await columnRepository.update(column.id, {
              isPrimaryCode: nextPrimary,
              isDescription: nextDescription,
              isSearchable: nextPrimary || nextDescription || column.isSearchable,
            });
          } else {
            column.isPrimaryCode = nextPrimary;
            column.isDescription = nextDescription;
            column.isSearchable = nextPrimary || nextDescription || column.isSearchable;
          }
        }
      }

      if (options.persist) {
        columns = await columnRepository.findByFolderIdOrdered(folderId);
      }
    }

    if (config.useGeneratedPrimaryCodes) {
      columns = await this.syncGeneratedPrimaryCodeColumn(folderId, columns, options.persist);
      columns = await this.clearImageCodeFlagsWithoutZip(
        folderId,
        columns,
        options.persist,
      );
    }

    return columns;
  }

  /**
   * Without a ZIP there is no image-code linking. Clear stale isImageCode flags
   * (e.g. plain "IMAGEN" headers from older imports) so the folder is not treated
   * as ZIP-linked.
   */
  private async clearImageCodeFlagsWithoutZip(
    folderId: string,
    columns: Awaited<ReturnType<typeof columnRepository.findByFolderIdOrdered>>,
    persist: boolean,
  ) {
    let changed = false;

    for (const column of columns) {
      if (!column.isImageCode) {
        continue;
      }

      changed = true;
      if (persist) {
        await columnRepository.update(column.id, { isImageCode: false });
      } else {
        column.isImageCode = false;
      }
    }

    if (changed && persist) {
      return columnRepository.findByFolderIdOrdered(folderId);
    }

    return columns;
  }

  private toPreviewFolderColumn(
    data: Parameters<typeof columnRepository.create>[0],
  ): Awaited<ReturnType<typeof columnRepository.findByFolderIdOrdered>>[number] {
    const now = new Date(0);

    return {
      id: `preview:${data.internalKey}`,
      folderId: data.folderId,
      originalName: data.originalName,
      displayName: data.displayName,
      internalKey: data.internalKey,
      dataType: data.dataType ?? "UNKNOWN",
      order: data.order ?? 0,
      visibleToNormalUser: data.visibleToNormalUser ?? true,
      isSearchable: data.isSearchable ?? false,
      isGloballySearchable: data.isGloballySearchable ?? false,
      isFilterable: data.isFilterable ?? false,
      isGloballyFilterable: data.isGloballyFilterable ?? false,
      isAdminEditable: data.isAdminEditable ?? true,
      isPrimaryCode: data.isPrimaryCode ?? false,
      isEquivalence: data.isEquivalence ?? false,
      isDescription: data.isDescription ?? false,
      isImageCode: data.isImageCode ?? false,
      isRequired: data.isRequired ?? false,
      isReadOnly: data.isReadOnly ?? false,
      width: data.width ?? null,
      format: data.format ?? null,
      unit: data.unit ?? null,
      label: data.label ?? null,
      globalFieldKey: data.globalFieldKey ?? null,
      helpText: data.helpText ?? null,
      helpImageAltText: data.helpImageAltText ?? null,
      helpImagePath: data.helpImagePath ?? null,
      helpImageThumbnailPath: data.helpImageThumbnailPath ?? null,
      helpImageMimeType: data.helpImageMimeType ?? null,
      helpImageSizeBytes: data.helpImageSizeBytes ?? null,
      helpImageOriginalName: data.helpImageOriginalName ?? null,
      createdAt: now,
      updatedAt: now,
    };
  }

  private async syncGeneratedPrimaryCodeColumn(
    folderId: string,
    columns: Awaited<ReturnType<typeof columnRepository.findByFolderIdOrdered>>,
    persist = true,
  ) {
    const hasGeneratedColumn = columns.some(
      (column) => column.internalKey === GENERATED_PRIMARY_CODE_COLUMN_KEY,
    );

    if (!hasGeneratedColumn) {
      for (const column of columns) {
        if (!column.isPrimaryCode) {
          continue;
        }

        if (persist) {
          await columnRepository.update(column.id, {
            isPrimaryCode: false,
            isSearchable: column.isDescription || column.isSearchable,
          });
        } else {
          column.isPrimaryCode = false;
          column.isSearchable = column.isDescription || column.isSearchable;
        }
      }

      if (persist) {
        await columnRepository.create({
          folderId,
          originalName: GENERATED_PRIMARY_CODE_DISPLAY_NAME,
          displayName: GENERATED_PRIMARY_CODE_DISPLAY_NAME,
          internalKey: GENERATED_PRIMARY_CODE_COLUMN_KEY,
          dataType: "TEXT",
          order: columns.length,
          isPrimaryCode: true,
          isDescription: false,
          isImageCode: false,
          isSearchable: true,
          isFilterable: false,
        });
        columns = await columnRepository.findByFolderIdOrdered(folderId);
      } else {
        columns = [
          ...columns,
          this.toPreviewFolderColumn({
            folderId,
            originalName: GENERATED_PRIMARY_CODE_DISPLAY_NAME,
            displayName: GENERATED_PRIMARY_CODE_DISPLAY_NAME,
            internalKey: GENERATED_PRIMARY_CODE_COLUMN_KEY,
            dataType: "TEXT",
            order: columns.length,
            isPrimaryCode: true,
            isDescription: false,
            isImageCode: false,
            isSearchable: true,
            isFilterable: false,
          }),
        ];
      }
    }

    for (const column of columns) {
      const nextPrimary = column.internalKey === GENERATED_PRIMARY_CODE_COLUMN_KEY;

      if (column.isPrimaryCode !== nextPrimary) {
        if (persist) {
          await columnRepository.update(column.id, {
            isPrimaryCode: nextPrimary,
            isSearchable: nextPrimary || column.isDescription || column.isSearchable,
          });
        } else {
          column.isPrimaryCode = nextPrimary;
          column.isSearchable = nextPrimary || column.isDescription || column.isSearchable;
        }
      }
    }

    if (persist) {
      return columnRepository.findByFolderIdOrdered(folderId);
    }

    return columns;
  }

  async buildPreview(jobId: string, configOverride?: ImportJobConfig) {
    await requireAdmin();
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    const config = configOverride ?? ((job.config as ImportJobConfig | null) ?? {});
    const sheet = await this.loadTargetSheet(job);

    if (job.destinationType === "PRICE_LIST") {
      if (!job.priceListId) {
        throw new ImportError("Debe seleccionar lista de precios destino.", "VALIDATION_ERROR");
      }
      return priceImportService.buildPreview(jobId, sheet, job.priceListId, config);
    }

    if (!job.folderId) {
      throw new ImportError("Debe seleccionar carpeta destino.", "VALIDATION_ERROR");
    }

    const columnsBeforeSync = await columnRepository.findByFolderIdOrdered(job.folderId);
    const columns = await this.syncColumnsFromSheet(job.folderId, sheet, config, {
      persist: false,
    });
    const repeatedColumns = findRepeatedColumnNames(sheet.headers, columnsBeforeSync, config);

    const mappedProducts = mapSheetToProducts(sheet, columns, config);
    const existingProducts = await productRepository.findForMatchingByFolder(job.folderId);
    const matchKeys = columnsBeforeSync.map((column) => column.internalKey);
    const codeIndex = buildExistingCodeIndex(existingProducts);
    const contentIndex = buildExistingContentIndex(existingProducts, {
      allowedKeys: matchKeys,
    });
    const preferContentMatch = Boolean(config.useGeneratedPrimaryCodes);

    const recognizedProducts = mappedProducts.map((product) => {
      const matchedProductId = resolveImportProductMatchId(
        product,
        { codeIndex, contentIndex },
        { allowedKeys: matchKeys, preferContentMatch },
      );
      return {
        ...product,
        isMatch: Boolean(matchedProductId),
        ...(matchedProductId ? { matchedProductId } : {}),
      };
    });

    const matchedProducts = recognizedProducts.filter((product) => product.isMatch);
    const allWarnings = recognizedProducts.flatMap((product) => product.warnings);
    const formulaStats = countFormulas(recognizedProducts);
    const productCount = await productRepository.countByFolder(job.folderId);

    const summary = {
      totalProducts: recognizedProducts.length,
      matchedCount: matchedProducts.length,
      imageCount: sheet.embeddedImageSummary.embeddedImagesDetected,
      embeddedImagesDetected: sheet.embeddedImageSummary.embeddedImagesDetected,
      rowsWithEmbeddedImages: sheet.embeddedImageSummary.rowsWithEmbeddedImages,
      productsWithMultipleEmbeddedImages:
        sheet.embeddedImageSummary.productsWithMultipleEmbeddedImages,
      columnCount: sheet.columnCount,
      folderProductCount: productCount,
      folderIsEmpty: productCount === 0,
      formulasDetected: formulaStats.formulasDetected,
      formulasWithoutCachedValue: formulaStats.formulasWithoutCachedValue,
      repeatedColumns,
    };

    await importJobRepository.upsertPreview({
      importJobId: jobId,
      recognizedProducts: toPrismaJsonValue(recognizedProducts),
      matchedProducts: toPrismaJsonValue(matchedProducts),
      errors: [],
      warnings: allWarnings,
      summary: toPrismaJsonValue(summary),
    });

    return importJobRepository.update(jobId, {
      status: "READY_TO_APPLY",
      progress: {
        phase: "ready",
        percent: 90,
        message: "Vista previa lista. Confirme la acción de importación.",
      },
    });
  }

  private async summarizeEmbeddedImageReport(
    importJobId: string,
    sheet: ParsedSheet,
  ): Promise<{
    extracted: number;
    associated: number;
    pendingReview: number;
    rejected: number;
    rowsWithEmbeddedImages: number;
    productsWithEmbeddedImages: number;
    productsWithMultipleEmbeddedImages: number;
  }> {
    const embeddedImages = await productImageRepository.findEmbeddedByImportJob(importJobId);
    const associatedStatuses = new Set<ProductImageStatus>([
      "ASSOCIATED_AUTO",
      "ASSOCIATED_MANUAL",
    ]);
    const imagesByProduct = new Map<string, number>();

    let associated = 0;
    let pendingReview = 0;
    let rejected = 0;

    for (const image of embeddedImages) {
      if (associatedStatuses.has(image.status)) {
        associated += 1;

        if (image.productId) {
          imagesByProduct.set(
            image.productId,
            (imagesByProduct.get(image.productId) ?? 0) + 1,
          );
        }
      } else if (image.status === "PENDING_REVIEW") {
        pendingReview += 1;
      } else if (image.status === "FORMAT_REJECTED") {
        rejected += 1;
      }
    }

    const productsWithMultipleEmbeddedImages = Array.from(imagesByProduct.values()).filter(
      (count) => count > 1,
    ).length;

    return {
      extracted: embeddedImages.length,
      associated,
      pendingReview,
      rejected,
      rowsWithEmbeddedImages: sheet.embeddedImageSummary.rowsWithEmbeddedImages,
      productsWithEmbeddedImages: imagesByProduct.size,
      productsWithMultipleEmbeddedImages,
    };
  }

  async apply(jobId: string, input: ApplyImportInput) {
    const { profile: admin } = await requireAdmin();
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    assertStatus(
      job.status,
      isImageProcessingResume(job) ? ["READY_TO_APPLY", "PROCESSING"] : ["READY_TO_APPLY"],
    );

    const resumingImages = isImageProcessingResume(job);

    if (resumingImages && job.actionType && job.actionType !== input.actionType) {
      throw new ImportError(
        "La importación se interrumpió con otra acción. Use la misma opción para reintentar.",
        "INVALID_STATE",
      );
    }

    if (!job.preview) {
      throw new ImportError("La importación no tiene vista previa.", "INVALID_STATE");
    }

    if (job.destinationType === "PRICE_LIST") {
      if (!job.priceListId) {
        throw new ImportError("Lista de precios destino no encontrada.", "VALIDATION_ERROR");
      }

      const config = (job.config as ImportJobConfig | null) ?? {};
      const sheet = await this.loadTargetSheet(job);
      const previewItems = job.preview.recognizedProducts as MappedPriceItemRow[];

      await priceImportService.apply(
        jobId,
        input,
        admin.id,
        sheet,
        job.priceListId,
        config,
        previewItems,
      );

      return importJobRepository.findByIdWithRelations(jobId);
    }

    if (!job.folderId) {
      throw new ImportError("Carpeta destino no encontrada.", "VALIDATION_ERROR");
    }

    const folder = await folderRepository.findByIdWithProductCount(job.folderId);
    if (!folder) {
      throw new ImportError("Carpeta destino no encontrada.", "VALIDATION_ERROR");
    }

    const productCount = folder.productCount;
    const recognizedProducts = job.preview.recognizedProducts as MappedProductRow[];

    if (!resumingImages && input.actionType === "IMPORTAR_LISTA" && productCount > 0) {
      throw new ImportError(
        "La carpeta no está vacía. Use combinar o reemplazar.",
        "FOLDER_NOT_EMPTY",
      );
    }

    if (
      !resumingImages &&
      (input.actionType === "COMBINAR_LISTA" ||
        input.actionType === "REEMPLAZAR_LISTA") &&
      !input.confirmed
    ) {
      throw new ImportError(
        "Debe confirmar la operación antes de aplicar.",
        "CONFIRMATION_REQUIRED",
      );
    }

    const config = (job.config as ImportJobConfig | null) ?? {};
    const sheet = await this.loadTargetSheet(job);
    const columnsBeforeSync = await columnRepository.findByFolderIdOrdered(job.folderId);
    await this.pruneOrphanAutoGeneratedColumns(job.folderId, sheet);
    const columns = await this.syncColumnsFromSheet(job.folderId, sheet, config, {
      persist: true,
      replaceSchema: input.actionType === "REEMPLAZAR_LISTA",
    });
    const mappedProducts = mapSheetToProducts(sheet, columns, config);

    let productsToInsert = mappedProducts;

    if (input.actionType === "COMBINAR_LISTA") {
      const existingProducts = await productRepository.findForMatchingByFolder(job.folderId);
      const matchKeys = columnsBeforeSync.map((column) => column.internalKey);
      const codeIndex = buildExistingCodeIndex(existingProducts);
      const contentIndex = buildExistingContentIndex(existingProducts, {
        allowedKeys: matchKeys,
      });
      const preferContentMatch = Boolean(config.useGeneratedPrimaryCodes);

      productsToInsert = mappedProducts.filter(
        (product) =>
          !resolveImportProductMatchId(
            product,
            { codeIndex, contentIndex },
            { allowedKeys: matchKeys, preferContentMatch },
          ),
      );
    }

    const skippedCount = mappedProducts.length - productsToInsert.length;
    const matchedCount =
      input.actionType === "COMBINAR_LISTA"
        ? skippedCount
        : (job.preview.matchedProducts as unknown[]).length;

    let reachedImageProcessing = resumingImages;

    try {
      if (!resumingImages) {
        await prisma.$transaction(async () => {
          if (input.actionType === "REEMPLAZAR_LISTA") {
            await productRepository.deleteByFolder(job.folderId!);
          }

          for (let offset = 0; offset < productsToInsert.length; offset += BATCH_SIZE) {
            const batch = productsToInsert.slice(offset, offset + BATCH_SIZE);
            await productRepository.createMany(
              batch.map((product) => {
                const indexedText = buildIndexedTextForMappedProduct(
                  columns,
                  product,
                );
                return {
                  folderId: job.folderId!,
                  primaryCode: product.primaryCode,
                  normalizedCode: product.normalizedCode,
                  description: product.description,
                  dynamicData: product.dynamicData,
                  originalText: product.originalText,
                  indexedText,
                  normalizedIndexedText: normalizeIndexedText(indexedText),
                };
              }),
            );
          }
        });

        const folderProducts = await productRepository.findByFolderId(job.folderId!);
        await equivalenceService.syncManyFromProducts(
          folderProducts.map((product) => {
            const dynamicData =
              typeof product.dynamicData === "object" &&
              product.dynamicData !== null &&
              !Array.isArray(product.dynamicData)
                ? (product.dynamicData as Record<string, unknown>)
                : {};

            return { id: product.id, dynamicData };
          }),
          columns,
        );
      }

      reachedImageProcessing = true;

      await importJobRepository.update(jobId, {
        status: "PROCESSING",
        actionType: input.actionType,
        progress: {
          phase: "images",
          percent: 85,
          message: "Procesando imágenes...",
        },
      });

      const workbook = await this.loadWorkbookFromJob(job);
      const productsForImages =
        input.actionType === "COMBINAR_LISTA" ? productsToInsert : mappedProducts;
      const imageProcessing = await this.processImportImages({
        jobId,
        folderId: job.folderId!,
        sheet,
        mappedProducts: productsForImages,
        config,
        columns,
        workbook,
        skipUnmatchedEmbeddedRows: input.actionType === "COMBINAR_LISTA",
      });

      const embeddedReport = await this.summarizeEmbeddedImageReport(jobId, sheet);

      const pendingCount = await productImageRepository.countByImportJobAndStatuses(
        jobId,
        ["PENDING_REVIEW", "AMBIGUOUS"],
      );

      const finalStatus: ImportJobStatus =
        pendingCount > 0 ? "PENDING_REVIEW" : "PUBLISHED";

      const formulaStats = countFormulas(mappedProducts);
      const report: ImportReport = {
        fileName: job.uploadedFile.originalName,
        catalogName: job.catalog?.name ?? null,
        folderName: job.folder?.name ?? null,
        sheetImported: job.targetSheetName,
        sheetsDetected: job.sheets.length,
        productsProcessed: mappedProducts.length,
        productsCreated: resumingImages ? 0 : productsToInsert.length,
        productsSkipped: skippedCount,
        productsMatched: matchedCount,
        formulasDetected: formulaStats.formulasDetected,
        formulasWithoutCachedValue: formulaStats.formulasWithoutCachedValue,
        imagesDetected: sheet.embeddedImageSummary.embeddedImagesDetected,
        imagesExtracted: embeddedReport.extracted,
        imagesAssociated: imageProcessing.stats.associated,
        imagesPendingReview: pendingCount,
        imagesRejected: imageProcessing.stats.rejected,
        imagesAmbiguous: imageProcessing.stats.ambiguous,
        embeddedImagesDetected: sheet.embeddedImageSummary.embeddedImagesDetected,
        embeddedImagesAssociated: embeddedReport.associated,
        embeddedImagesPendingReview: embeddedReport.pendingReview,
        embeddedImagesRejected: embeddedReport.rejected,
        rowsWithEmbeddedImages: embeddedReport.rowsWithEmbeddedImages,
        productsWithEmbeddedImages: embeddedReport.productsWithEmbeddedImages,
        productsWithMultipleEmbeddedImages:
          embeddedReport.productsWithMultipleEmbeddedImages,
        columnsDetected: sheet.columnCount,
        columnsCreated: columns.length,
        errors: [],
        warnings: [
          ...recognizedProducts.flatMap((product) => product.warnings),
          ...imageProcessing.warnings,
        ],
        actionApplied: input.actionType,
      };

      const updated = await importJobRepository.update(jobId, {
        status: finalStatus,
        actionType: input.actionType,
        resultados: report as unknown as Prisma.InputJsonValue,
        finishedAt: finalStatus === "PUBLISHED" ? new Date() : null,
        progress: {
          phase: finalStatus === "PENDING_REVIEW" ? "image_review" : "published",
          percent: finalStatus === "PENDING_REVIEW" ? 95 : 100,
          message:
            finalStatus === "PENDING_REVIEW"
              ? "Importación aplicada. Revise las asociaciones de imágenes pendientes."
              : "Importación publicada correctamente.",
        },
      });

      if (finalStatus === "PUBLISHED") {
        auditService.logOperationSafe({
          userId: admin.id,
          action: AUDIT_ACTIONS.IMPORT_PUBLISHED,
          entityType: AUDIT_ENTITY_TYPES.IMPORT,
          entityId: jobId,
        });
      }

      return updated;
    } catch (error) {
      console.error("[catalogImportService.publish]", error);

      if (reachedImageProcessing) {
        await importJobRepository.update(jobId, {
          status: "PROCESSING",
          actionType: input.actionType,
          errorMessage: null,
          progress: {
            phase: "images",
            percent: 85,
            message: "Procesamiento de imágenes interrumpido. Puede reintentar.",
          },
        });

        throw new ImportError(
          "El procesamiento de imágenes fue interrumpido. Pulse importar de nuevo para continuar.",
          "IMAGE_PROCESSING_INTERRUPTED",
        );
      }

      const clientMessage = "Error al publicar la importación.";

      await importJobRepository.update(jobId, {
        status: "FAILED",
        errorMessage: clientMessage,
        finishedAt: new Date(),
        progress: { phase: "failed", percent: 100, message: clientMessage },
      });

      await uploadedFileRetentionService.purgeIfWithoutRetainedImport(job.uploadedFileId);
      throw new ImportError(clientMessage, "PUBLISH_FAILED");
    }
  }

  async cancel(jobId: string) {
    await requireAdmin();
    const job = await importJobRepository.findById(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    if (TERMINAL_STATUSES.includes(job.status)) {
      throw new ImportError("La importación ya finalizó.", "INVALID_STATE");
    }

    const updated = await importJobRepository.update(jobId, {
      status: "CANCELLED",
      finishedAt: new Date(),
      progress: {
        phase: "cancelled",
        percent: 100,
        message: "Importación cancelada.",
      },
    });

    await uploadedFileRetentionService.purgeIfWithoutRetainedImport(job.uploadedFileId);

    return updated;
  }
}

export const catalogImportService = new CatalogImportService();
