import type {
  ImportActionType,
  ImportJobStatus,
  ImportSheetClassification,
  Prisma,
} from "@/generated/prisma/client";
import ExcelJS from "exceljs";
import { requireRole } from "@/server/auth";
import {
  buildExistingCodeIndex,
  detectSemanticFlags,
  findMatchingProductId,
  mapSheetToProducts,
  parseWorkbookFromBuffer,
  toExcelJsBuffer,
  type ImportJobConfig,
  type MappedProductRow,
  type ParsedSheet,
  type DetectedHeader,
} from "@/server/importers";
import {
  GENERATED_PRIMARY_CODE_COLUMN_KEY,
  GENERATED_PRIMARY_CODE_DISPLAY_NAME,
} from "@/server/importers/generated-primary-code";
import { extractImagesFromZip, ZipExtractionError } from "@/server/image-processors/zip-extractor";
import { columnRepository } from "@/server/repositories/column.repository";
import { importJobRepository } from "@/server/repositories/import-job.repository";
import { productImageRepository } from "@/server/repositories/product-image.repository";
import { productRepository } from "@/server/repositories/product.repository";
import { uploadedFileRepository } from "@/server/repositories/uploaded-file.repository";
import { catalogRepository } from "@/server/repositories/catalog.repository";
import { folderRepository } from "@/server/repositories/folder.repository";
import { buildIndexedTextForMappedProduct } from "@/server/services/product-field.builder";
import { prisma } from "@/server/database/prisma";
import {
  buildStoragePath,
  downloadFile,
  uploadFile,
} from "@/server/storage";
import { STORAGE_BUCKETS } from "@/server/storage/types";
import { StorageError } from "@/server/storage/errors";
import { imageExtractionService } from "./image-extraction.service";
import { productImageService } from "./product-image.service";
import { equivalenceService } from "./equivalence.service";
import { AUDIT_ACTIONS, AUDIT_ENTITY_TYPES } from "./audit.constants";
import { auditService } from "./audit.service";
import { ImportError } from "./import.errors";

const BATCH_SIZE = 500;

function isAutoGeneratedColumnName(name: string): boolean {
  return /^columna \d+$/i.test(name.trim());
}

const TERMINAL_STATUSES: ImportJobStatus[] = [
  "PUBLISHED",
  "FAILED",
  "CANCELLED",
];

export type UploadImportFileInput = {
  buffer: Buffer;
  originalFilename: string;
  contentType: string;
};

export type UploadImportImageInput = {
  buffer: Buffer;
  originalFilename: string;
  contentType: string;
  isZip: boolean;
};

export type SetImportDestinationInput = {
  catalogId: string;
  folderId: string;
  sheetName: string;
};

export type SetImportConfigInput = ImportJobConfig;

export type ApplyImportInput = {
  actionType: ImportActionType;
  confirmed: boolean;
};

export type ImportProgress = {
  phase: string;
  percent: number;
  message: string;
};

export type ImportReport = {
  fileName: string;
  catalogName: string | null;
  folderName: string | null;
  sheetImported: string | null;
  sheetsDetected: number;
  productsProcessed: number;
  productsCreated: number;
  productsSkipped: number;
  productsMatched: number;
  formulasDetected: number;
  formulasWithoutCachedValue: number;
  imagesDetected: number;
  imagesExtracted: number;
  imagesAssociated: number;
  imagesPendingReview: number;
  imagesRejected: number;
  imagesAmbiguous: number;
  columnsDetected: number;
  columnsCreated: number;
  errors: string[];
  warnings: string[];
  actionApplied: ImportActionType | null;
};

function assertStatus(current: ImportJobStatus, allowed: ImportJobStatus[]): void {
  if (!allowed.includes(current)) {
    throw new ImportError(
      `Estado de importación inválido: ${current}.`,
      "INVALID_STATE",
    );
  }
}

function toClassification(
  classification: ParsedSheet["classification"],
): ImportSheetClassification {
  return classification;
}

function countFormulas(products: MappedProductRow[]): {
  formulasDetected: number;
  formulasWithoutCachedValue: number;
} {
  let formulasDetected = 0;
  let formulasWithoutCachedValue = 0;

  for (const product of products) {
    for (const formula of product.formulas) {
      formulasDetected += 1;
      if (!formula.hasCachedValue) {
        formulasWithoutCachedValue += 1;
      }
    }
  }

  return { formulasDetected, formulasWithoutCachedValue };
}

export class CatalogImportService {
  async uploadAndCreateJob(input: UploadImportFileInput) {
    const { profile: admin } = await requireRole("ADMIN");

    let uploaded;
    try {
      uploaded = await uploadFile({
        bucket: STORAGE_BUCKETS.EXCEL_ORIGINALS,
        path: buildStoragePath("imports", input.originalFilename),
        body: input.buffer,
        contentType: input.contentType,
        originalFilename: input.originalFilename,
        auditContext: { userId: admin.id },
      });
    } catch (error) {
      if (error instanceof StorageError) {
        throw new ImportError(error.message, "INVALID_FILE");
      }
      throw error;
    }

    const uploadedFile = await uploadedFileRepository.create({
      originalName: input.originalFilename,
      storagePath: uploaded.path,
      mimeType: uploaded.contentType,
      sizeBytes: uploaded.sizeBytes,
      uploadedById: admin.id,
    });

    const job = await importJobRepository.create({
      uploadedFileId: uploadedFile.id,
      status: "STORED",
    });

    return { jobId: job.id, uploadedFileId: uploadedFile.id };
  }

  async getJob(jobId: string) {
    await requireRole("ADMIN");
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    return job;
  }

  async analyzeJob(jobId: string) {
    await requireRole("ADMIN");
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    assertStatus(job.status, ["STORED", "PENDING_DESTINATION"]);

    await importJobRepository.update(jobId, {
      status: "ANALYZING",
      progress: { phase: "analyze", percent: 10, message: "Analizando archivo..." },
      errorMessage: null,
    });

    try {
      const buffer = await downloadFile(
        STORAGE_BUCKETS.EXCEL_ORIGINALS,
        job.uploadedFile.storagePath,
      );
      const workbook = await parseWorkbookFromBuffer(buffer);

      await importJobRepository.replaceSheets(
        jobId,
        workbook.sheets.map((sheet) => ({
          importJobId: jobId,
          sheetName: sheet.sheetName,
          classification: toClassification(sheet.classification),
          rowCount: sheet.rowCount,
          columnCount: sheet.columnCount,
          detectedHeaders: sheet.headers,
          metadata: {
            classificationReason: sheet.classificationReason,
            headerRow: sheet.headerRow,
            imageCount: sheet.imageCount,
          },
        })),
      );

      await uploadedFileRepository.updateStatus(job.uploadedFileId, "PROCESSED");

      return importJobRepository.update(jobId, {
        status: "PENDING_DESTINATION",
        progress: {
          phase: "destination",
          percent: 40,
          message: "Seleccione catálogo, carpeta y hoja destino.",
        },
      });
    } catch (error) {
      console.error("[catalogImportService.analyzeJob]", error);
      const clientMessage = "Error al analizar el archivo.";

      await importJobRepository.update(jobId, {
        status: "FAILED",
        errorMessage: clientMessage,
        finishedAt: new Date(),
        progress: { phase: "failed", percent: 100, message: clientMessage },
      });

      await uploadedFileRepository.updateStatus(job.uploadedFileId, "FAILED");
      throw new ImportError(clientMessage, "ANALYSIS_FAILED");
    }
  }

  async setDestination(jobId: string, input: SetImportDestinationInput) {
    await requireRole("ADMIN");
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    assertStatus(job.status, ["PENDING_DESTINATION", "PENDING_CONFIG", "READY_TO_APPLY"]);

    const sheet = job.sheets.find((item) => item.sheetName === input.sheetName);
    if (!sheet) {
      throw new ImportError("Hoja no encontrada en el archivo.", "VALIDATION_ERROR");
    }

    if (sheet.classification !== "IMPORTABLE") {
      throw new ImportError(
        "La hoja seleccionada no es importable.",
        "SHEET_NOT_IMPORTABLE",
      );
    }

    const folder = await folderRepository.findById(input.folderId);
    if (!folder || folder.catalogId !== input.catalogId) {
      throw new ImportError("Carpeta destino inválida.", "VALIDATION_ERROR");
    }

    const catalog = await catalogRepository.findById(input.catalogId);
    if (!catalog) {
      throw new ImportError("Catálogo destino inválido.", "VALIDATION_ERROR");
    }

    await importJobRepository.deletePreview(jobId);

    return importJobRepository.update(jobId, {
      catalogId: input.catalogId,
      folderId: input.folderId,
      targetSheetName: input.sheetName,
      status: "PENDING_CONFIG",
      progress: {
        phase: "config",
        percent: 55,
        message: "Configure columnas y genere la vista previa.",
      },
    });
  }

  async setConfig(jobId: string, input: SetImportConfigInput) {
    await requireRole("ADMIN");
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    assertStatus(job.status, ["PENDING_CONFIG", "READY_TO_APPLY"]);

    const existingConfig = (job.config as ImportJobConfig | null) ?? {};
    const config: ImportJobConfig = {
      ...existingConfig,
      columnMapping: input.columnMapping,
      primaryCodeColumnKey: input.useGeneratedPrimaryCodes
        ? undefined
        : input.primaryCodeColumnKey,
      descriptionColumnKey: input.descriptionColumnKey,
      useGeneratedPrimaryCodes: input.useGeneratedPrimaryCodes ?? false,
    };

    await importJobRepository.update(jobId, {
      config,
      status: "PROCESSING",
      progress: {
        phase: "preview",
        percent: 70,
        message: "Generando vista previa...",
      },
    });

    return this.buildPreview(jobId, config);
  }

  private async loadWorkbookFromJob(
    job: NonNullable<Awaited<ReturnType<typeof importJobRepository.findByIdWithRelations>>>,
  ): Promise<ExcelJS.Workbook> {
    const buffer = await downloadFile(
      STORAGE_BUCKETS.EXCEL_ORIGINALS,
      job.uploadedFile.storagePath,
    );
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(toExcelJsBuffer(buffer));
    return workbook;
  }

  private async buildRowToProductMap(
    folderId: string,
    mappedProducts: MappedProductRow[],
  ): Promise<Map<number, string>> {
    const products = await productRepository.findPrimaryCodesByFolder(folderId);
    const index = buildExistingCodeIndex(products);
    const map = new Map<number, string>();

    for (const row of mappedProducts) {
      const productId = findMatchingProductId(row.primaryCode, index);
      if (productId) {
        map.set(row.rowNumber, productId);
      }
    }

    return map;
  }

  private async processImportImages(input: {
    jobId: string;
    folderId: string;
    sheet: ParsedSheet;
    mappedProducts: MappedProductRow[];
    config: ImportJobConfig;
    columns: Awaited<ReturnType<typeof columnRepository.findByFolderIdOrdered>>;
    workbook: ExcelJS.Workbook;
  }): Promise<{
    warnings: string[];
    stats: {
      extracted: number;
      associated: number;
      pendingReview: number;
      rejected: number;
      ambiguous: number;
    };
  }> {
    const warnings: string[] = [];
    const stats = {
      extracted: 0,
      associated: 0,
      pendingReview: 0,
      rejected: 0,
      ambiguous: 0,
    };

    const rowToProductId = await this.buildRowToProductMap(
      input.folderId,
      input.mappedProducts,
    );

    if (input.sheet.imageCount > 0) {
      const embedded = await imageExtractionService.processEmbeddedImages({
        workbook: input.workbook,
        sheet: input.sheet,
        folderId: input.folderId,
        importJobId: input.jobId,
        rowToProductId,
      });

      warnings.push(...embedded.warnings);
      stats.extracted += embedded.stats.extracted;
      stats.associated += embedded.stats.associated;
      stats.pendingReview += embedded.stats.pendingReview;
      stats.rejected += embedded.stats.rejected;
      stats.ambiguous += embedded.stats.ambiguous;
    }

    const externalImages = input.config.externalImages ?? [];
    if (externalImages.length > 0) {
      const imageInputs = await Promise.all(
        externalImages.map(async (ref) => ({
          buffer: await downloadFile(STORAGE_BUCKETS.TEMP_IMPORTS, ref.storagePath),
          originalName: ref.originalName,
          mimeType: ref.mimeType,
          source: ref.source,
        })),
      );

      const imageCodeColumnKeys = input.columns
        .filter((column) => column.isImageCode)
        .map((column) => column.internalKey);

      const external = await productImageService.processExternalImages({
        importJobId: input.jobId,
        folderId: input.folderId,
        images: imageInputs,
        imageCodeColumnKeys,
        includePrimaryCodeInMatch: !input.config.useGeneratedPrimaryCodes,
      });

      warnings.push(...external.warnings);
      stats.extracted += external.stats.processed;
      stats.associated += external.stats.associated;
      stats.pendingReview += external.stats.pendingReview;
      stats.rejected += external.stats.rejected;
      stats.ambiguous += external.stats.ambiguous;
    }

    return { warnings, stats };
  }

  async uploadImportImages(jobId: string, files: UploadImportImageInput[]) {
    await requireRole("ADMIN");
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    assertStatus(job.status, [
      "STORED",
      "PENDING_DESTINATION",
      "PENDING_CONFIG",
      "READY_TO_APPLY",
    ]);

    const config = (job.config as ImportJobConfig | null) ?? {};
    const externalImages = [...(config.externalImages ?? [])];

    for (const file of files) {
      if (file.isZip) {
        let extracted;
        try {
          extracted = await extractImagesFromZip(file.buffer);
        } catch (error) {
          if (error instanceof ZipExtractionError) {
            throw new ImportError(error.message, "INVALID_FILE");
          }
          throw error;
        }

        for (const entry of extracted) {
          const staged = await productImageService.uploadExternalToStaging({
            jobId,
            buffer: entry.buffer,
            originalFilename: entry.originalName,
            contentType: "application/octet-stream",
            source: "EXTERNAL_ZIP",
          });
          externalImages.push(staged);
        }
        continue;
      }

      const staged = await productImageService.uploadExternalToStaging({
        jobId,
        buffer: file.buffer,
        originalFilename: file.originalFilename,
        contentType: file.contentType,
        source: "EXTERNAL_UPLOAD",
      });
      externalImages.push(staged);
    }

    return importJobRepository.update(jobId, {
      config: {
        ...config,
        externalImages,
      } as unknown as Prisma.InputJsonValue,
    });
  }

  async completeImageReview(jobId: string) {
    const { profile: admin } = await requireRole("ADMIN");
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    assertStatus(job.status, ["PENDING_REVIEW"]);

    const updated = await importJobRepository.update(jobId, {
      status: "PUBLISHED",
      finishedAt: new Date(),
      progress: {
        phase: "published",
        percent: 100,
        message: "Revisión de imágenes completada. Importación publicada.",
      },
    });

    auditService.logOperationSafe({
      userId: admin.id,
      action: AUDIT_ACTIONS.IMPORT_PUBLISHED,
      entityType: AUDIT_ENTITY_TYPES.IMPORT,
      entityId: jobId,
    });

    return updated;
  }

  private async loadTargetSheet(job: NonNullable<Awaited<ReturnType<typeof importJobRepository.findByIdWithRelations>>>) {
    if (!job.targetSheetName) {
      throw new ImportError("Debe seleccionar una hoja destino.", "VALIDATION_ERROR");
    }

    const buffer = await downloadFile(
      STORAGE_BUCKETS.EXCEL_ORIGINALS,
      job.uploadedFile.storagePath,
    );
    const workbook = await parseWorkbookFromBuffer(buffer);
    const sheet = workbook.sheets.find((item) => item.sheetName === job.targetSheetName);

    if (!sheet) {
      throw new ImportError("Hoja destino no encontrada.", "VALIDATION_ERROR");
    }

    return sheet;
  }

  private async pruneOrphanAutoGeneratedColumns(
    folderId: string,
    sheet: ParsedSheet,
  ): Promise<void> {
    const columns = await columnRepository.findByFolderIdOrdered(folderId);
    const sheetOriginalNames = new Set(
      sheet.headers.map((header) => header.originalName.trim().toLowerCase()),
    );
    const sheetInternalKeys = new Set(
      sheet.headers.map((header) => header.internalKey),
    );

    for (const column of columns) {
      if (!isAutoGeneratedColumnName(column.originalName)) {
        continue;
      }

      if (column.isPrimaryCode || column.isDescription) {
        continue;
      }

      if (sheetOriginalNames.has(column.originalName.trim().toLowerCase())) {
        continue;
      }

      if (sheetInternalKeys.has(column.internalKey)) {
        continue;
      }

      const hasData = await productRepository.hasNonEmptyDynamicValue(
        folderId,
        column.internalKey,
      );

      if (!hasData) {
        await columnRepository.delete(column.id);
      }
    }
  }

  private resolveMappedFolderColumnKey(
    header: DetectedHeader,
    columns: Awaited<ReturnType<typeof columnRepository.findByFolderIdOrdered>>,
    config: ImportJobConfig,
  ): string | null {
    const mapping = new Map(
      (config.columnMapping ?? []).map((entry) => [
        entry.headerInternalKey,
        entry.folderColumnInternalKey,
      ]),
    );

    const mapped = mapping.get(header.internalKey);
    if (mapped === "__ignore__") {
      return null;
    }

    if (mapped) {
      return mapped;
    }

    const byName = columns.find(
      (column) =>
        column.originalName.trim().toLowerCase() ===
        header.originalName.trim().toLowerCase(),
    );

    return byName?.internalKey ?? header.internalKey;
  }

  private async syncColumnsFromSheet(
    folderId: string,
    sheet: ParsedSheet,
    config: ImportJobConfig,
  ) {
    let columns = await columnRepository.findByFolderIdOrdered(folderId);
    const activeHeaders = sheet.headers.filter((header) => {
      return this.resolveMappedFolderColumnKey(header, columns, config) !== null;
    });

    if (columns.length === 0) {
      const semanticUsed = { primary: false, description: false };
      const columnsToCreate = [];

      for (let index = 0; index < activeHeaders.length; index += 1) {
        const header = activeHeaders[index];
        const targetKey = this.resolveMappedFolderColumnKey(header, columns, config);
        if (!targetKey) {
          continue;
        }

        const flags = detectSemanticFlags(header.originalName);
        const isPrimaryCode = config.useGeneratedPrimaryCodes
          ? false
          : config.primaryCodeColumnKey
            ? config.primaryCodeColumnKey === targetKey
            : !semanticUsed.primary && flags.isPrimaryCode;
        const isDescription = config.descriptionColumnKey
          ? config.descriptionColumnKey === targetKey
          : !semanticUsed.description && flags.isDescription;

        if (isPrimaryCode) semanticUsed.primary = true;
        if (isDescription) semanticUsed.description = true;

        columnsToCreate.push({
          folderId,
          originalName: header.originalName,
          displayName: header.originalName,
          internalKey: targetKey,
          dataType: header.inferredDataType,
          order: index,
          isPrimaryCode,
          isDescription,
          isImageCode: flags.isImageCode,
          isSearchable: isPrimaryCode || isDescription,
          isFilterable: false,
        });
      }

      if (columnsToCreate.length > 0) {
        await columnRepository.createMany(columnsToCreate);
        columns = await columnRepository.findByFolderIdOrdered(folderId);
      }

      if (config.useGeneratedPrimaryCodes) {
        columns = await this.syncGeneratedPrimaryCodeColumn(folderId, columns);
      }

      return columns;
    }

    const existingKeys = new Set(columns.map((column) => column.internalKey));
    const existingNames = new Set(
      columns.map((column) => column.originalName.trim().toLowerCase()),
    );
    const columnsToCreate = [];

    for (let index = 0; index < activeHeaders.length; index += 1) {
      const header = activeHeaders[index];
      const targetKey = this.resolveMappedFolderColumnKey(header, columns, config);
      if (!targetKey) {
        continue;
      }

      if (existingKeys.has(targetKey)) {
        continue;
      }

      if (existingNames.has(header.originalName.trim().toLowerCase())) {
        continue;
      }

      const flags = detectSemanticFlags(header.originalName);
      columnsToCreate.push({
        folderId,
        originalName: header.originalName,
        displayName: header.originalName,
        internalKey: targetKey,
        dataType: header.inferredDataType,
        order: columns.length + index,
        isPrimaryCode:
          !config.useGeneratedPrimaryCodes && config.primaryCodeColumnKey === targetKey,
        isDescription: config.descriptionColumnKey === targetKey,
        isImageCode: flags.isImageCode,
        isSearchable:
          (!config.useGeneratedPrimaryCodes &&
            config.primaryCodeColumnKey === targetKey) ||
          config.descriptionColumnKey === targetKey,
        isFilterable: false,
      });
    }

    if (columnsToCreate.length > 0) {
      await columnRepository.createMany(columnsToCreate);
      columns = await columnRepository.findByFolderIdOrdered(folderId);
    }

    if (config.primaryCodeColumnKey || config.descriptionColumnKey) {
      for (const column of columns) {
        const nextPrimary =
          !config.useGeneratedPrimaryCodes &&
          column.internalKey === config.primaryCodeColumnKey;
        const nextDescription = column.internalKey === config.descriptionColumnKey;

        if (
          column.isPrimaryCode !== nextPrimary ||
          column.isDescription !== nextDescription
        ) {
          await columnRepository.update(column.id, {
            isPrimaryCode: nextPrimary,
            isDescription: nextDescription,
            isSearchable: nextPrimary || nextDescription || column.isSearchable,
          });
        }
      }

      columns = await columnRepository.findByFolderIdOrdered(folderId);
    }

    if (config.useGeneratedPrimaryCodes) {
      columns = await this.syncGeneratedPrimaryCodeColumn(folderId, columns);
    }

    return columns;
  }

  private async syncGeneratedPrimaryCodeColumn(
    folderId: string,
    columns: Awaited<ReturnType<typeof columnRepository.findByFolderIdOrdered>>,
  ) {
    const hasGeneratedColumn = columns.some(
      (column) => column.internalKey === GENERATED_PRIMARY_CODE_COLUMN_KEY,
    );

    if (!hasGeneratedColumn) {
      await columnRepository.create({
        folderId,
        originalName: GENERATED_PRIMARY_CODE_DISPLAY_NAME,
        displayName: GENERATED_PRIMARY_CODE_DISPLAY_NAME,
        internalKey: GENERATED_PRIMARY_CODE_COLUMN_KEY,
        dataType: "TEXT",
        order: columns.length,
        isPrimaryCode: true,
        isDescription: false,
        isImageCode: false,
        isSearchable: true,
        isFilterable: false,
      });
      columns = await columnRepository.findByFolderIdOrdered(folderId);
    }

    for (const column of columns) {
      const nextPrimary = column.internalKey === GENERATED_PRIMARY_CODE_COLUMN_KEY;

      if (column.isPrimaryCode !== nextPrimary) {
        await columnRepository.update(column.id, {
          isPrimaryCode: nextPrimary,
          isSearchable: nextPrimary || column.isDescription || column.isSearchable,
        });
      }
    }

    return columnRepository.findByFolderIdOrdered(folderId);
  }

  async buildPreview(jobId: string, configOverride?: ImportJobConfig) {
    await requireRole("ADMIN");
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    if (!job.folderId) {
      throw new ImportError("Debe seleccionar carpeta destino.", "VALIDATION_ERROR");
    }

    const config = configOverride ?? ((job.config as ImportJobConfig | null) ?? {});
    const sheet = await this.loadTargetSheet(job);
    await this.pruneOrphanAutoGeneratedColumns(job.folderId, sheet);
    const columns = await this.syncColumnsFromSheet(job.folderId, sheet, config);

    const mappedProducts = mapSheetToProducts(sheet, columns, config);
    const existingProducts = await productRepository.findPrimaryCodesByFolder(job.folderId);
    const matchIndex = buildExistingCodeIndex(existingProducts);

    const recognizedProducts = mappedProducts.map((product) => {
      const matchedProductId = findMatchingProductId(product.primaryCode, matchIndex);
      return {
        ...product,
        isMatch: Boolean(matchedProductId),
        matchedProductId,
      };
    });

    const matchedProducts = recognizedProducts.filter((product) => product.isMatch);
    const allWarnings = recognizedProducts.flatMap((product) => product.warnings);
    const formulaStats = countFormulas(recognizedProducts);
    const productCount = await productRepository.countByFolder(job.folderId);

    const summary = {
      totalProducts: recognizedProducts.length,
      matchedCount: matchedProducts.length,
      imageCount: sheet.imageCount,
      columnCount: sheet.columnCount,
      folderProductCount: productCount,
      folderIsEmpty: productCount === 0,
      formulasDetected: formulaStats.formulasDetected,
      formulasWithoutCachedValue: formulaStats.formulasWithoutCachedValue,
    };

    await importJobRepository.upsertPreview({
      importJobId: jobId,
      recognizedProducts: recognizedProducts as unknown as Prisma.InputJsonValue,
      matchedProducts: matchedProducts as unknown as Prisma.InputJsonValue,
      errors: [],
      warnings: allWarnings,
      summary: summary as unknown as Prisma.InputJsonValue,
    });

    return importJobRepository.update(jobId, {
      status: "READY_TO_APPLY",
      progress: {
        phase: "ready",
        percent: 90,
        message: "Vista previa lista. Confirme la acción de importación.",
      },
    });
  }

  async apply(jobId: string, input: ApplyImportInput) {
    const { profile: admin } = await requireRole("ADMIN");
    const job = await importJobRepository.findByIdWithRelations(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    assertStatus(job.status, ["READY_TO_APPLY"]);

    if (!job.folderId || !job.preview) {
      throw new ImportError("La importación no tiene vista previa.", "INVALID_STATE");
    }

    const folder = await folderRepository.findByIdWithProductCount(job.folderId);
    if (!folder) {
      throw new ImportError("Carpeta destino no encontrada.", "VALIDATION_ERROR");
    }

    const productCount = folder.productCount;
    const recognizedProducts = job.preview.recognizedProducts as MappedProductRow[];

    if (input.actionType === "IMPORTAR_LISTA" && productCount > 0) {
      throw new ImportError(
        "La carpeta no está vacía. Use combinar o reemplazar.",
        "FOLDER_NOT_EMPTY",
      );
    }

    if (
      (input.actionType === "COMBINAR_LISTA" ||
        input.actionType === "REEMPLAZAR_LISTA") &&
      !input.confirmed
    ) {
      throw new ImportError(
        "Debe confirmar la operación antes de aplicar.",
        "CONFIRMATION_REQUIRED",
      );
    }

    const config = (job.config as ImportJobConfig | null) ?? {};
    const sheet = await this.loadTargetSheet(job);
    const columns = await columnRepository.findByFolderIdOrdered(job.folderId);
    const mappedProducts = mapSheetToProducts(sheet, columns, config);

    let productsToInsert = mappedProducts;

    if (input.actionType === "COMBINAR_LISTA") {
      const existingProducts = await productRepository.findPrimaryCodesByFolder(job.folderId);
      const matchIndex = buildExistingCodeIndex(existingProducts);
      productsToInsert = mappedProducts.filter(
        (product) => !findMatchingProductId(product.primaryCode, matchIndex),
      );
    }

    const skippedCount = mappedProducts.length - productsToInsert.length;
    const matchedCount =
      input.actionType === "COMBINAR_LISTA"
        ? skippedCount
        : (job.preview.matchedProducts as unknown[]).length;

    try {
      await prisma.$transaction(async () => {
        if (input.actionType === "REEMPLAZAR_LISTA") {
          await productRepository.deleteByFolder(job.folderId!);
        }

        for (let offset = 0; offset < productsToInsert.length; offset += BATCH_SIZE) {
          const batch = productsToInsert.slice(offset, offset + BATCH_SIZE);
          await productRepository.createMany(
            batch.map((product) => ({
              folderId: job.folderId!,
              primaryCode: product.primaryCode,
              normalizedCode: product.normalizedCode,
              description: product.description,
              dynamicData: product.dynamicData,
              originalText: product.originalText,
              indexedText: buildIndexedTextForMappedProduct(columns, product),
            })),
          );
        }
      });

      const folderProducts = await productRepository.findByFolderId(job.folderId!);
      for (const product of folderProducts) {
        const dynamicData =
          typeof product.dynamicData === "object" &&
          product.dynamicData !== null &&
          !Array.isArray(product.dynamicData)
            ? (product.dynamicData as Record<string, unknown>)
            : {};

        await equivalenceService.syncFromProduct(product.id, columns, dynamicData);
      }

      await importJobRepository.update(jobId, {
        status: "PROCESSING",
        progress: {
          phase: "images",
          percent: 85,
          message: "Procesando imágenes...",
        },
      });

      const workbook = await this.loadWorkbookFromJob(job);
      const imageProcessing = await this.processImportImages({
        jobId,
        folderId: job.folderId!,
        sheet,
        mappedProducts,
        config,
        columns,
        workbook,
      });

      const pendingCount = await productImageRepository.countByImportJobAndStatuses(
        jobId,
        ["PENDING_REVIEW", "AMBIGUOUS"],
      );

      const finalStatus: ImportJobStatus =
        pendingCount > 0 ? "PENDING_REVIEW" : "PUBLISHED";

      const formulaStats = countFormulas(mappedProducts);
      const report: ImportReport = {
        fileName: job.uploadedFile.originalName,
        catalogName: job.catalog?.name ?? null,
        folderName: job.folder?.name ?? null,
        sheetImported: job.targetSheetName,
        sheetsDetected: job.sheets.length,
        productsProcessed: mappedProducts.length,
        productsCreated: productsToInsert.length,
        productsSkipped: skippedCount,
        productsMatched: matchedCount,
        formulasDetected: formulaStats.formulasDetected,
        formulasWithoutCachedValue: formulaStats.formulasWithoutCachedValue,
        imagesDetected: sheet.imageCount,
        imagesExtracted: imageProcessing.stats.extracted,
        imagesAssociated: imageProcessing.stats.associated,
        imagesPendingReview: pendingCount,
        imagesRejected: imageProcessing.stats.rejected,
        imagesAmbiguous: imageProcessing.stats.ambiguous,
        columnsDetected: sheet.columnCount,
        columnsCreated: columns.length,
        errors: [],
        warnings: [
          ...recognizedProducts.flatMap((product) => product.warnings),
          ...imageProcessing.warnings,
        ],
        actionApplied: input.actionType,
      };

      const updated = await importJobRepository.update(jobId, {
        status: finalStatus,
        actionType: input.actionType,
        resultados: report as unknown as Prisma.InputJsonValue,
        finishedAt: finalStatus === "PUBLISHED" ? new Date() : null,
        progress: {
          phase: finalStatus === "PENDING_REVIEW" ? "image_review" : "published",
          percent: finalStatus === "PENDING_REVIEW" ? 95 : 100,
          message:
            finalStatus === "PENDING_REVIEW"
              ? "Importación aplicada. Revise las asociaciones de imágenes pendientes."
              : "Importación publicada correctamente.",
        },
      });

      if (finalStatus === "PUBLISHED") {
        auditService.logOperationSafe({
          userId: admin.id,
          action: AUDIT_ACTIONS.IMPORT_PUBLISHED,
          entityType: AUDIT_ENTITY_TYPES.IMPORT,
          entityId: jobId,
        });
      }

      return updated;
    } catch (error) {
      console.error("[catalogImportService.publish]", error);
      const clientMessage = "Error al publicar la importación.";

      await importJobRepository.update(jobId, {
        status: "FAILED",
        errorMessage: clientMessage,
        finishedAt: new Date(),
        progress: { phase: "failed", percent: 100, message: clientMessage },
      });

      throw new ImportError(clientMessage, "PUBLISH_FAILED");
    }
  }

  async cancel(jobId: string) {
    await requireRole("ADMIN");
    const job = await importJobRepository.findById(jobId);

    if (!job) {
      throw new ImportError("Importación no encontrada.", "IMPORT_NOT_FOUND");
    }

    if (TERMINAL_STATUSES.includes(job.status)) {
      throw new ImportError("La importación ya finalizó.", "INVALID_STATE");
    }

    return importJobRepository.update(jobId, {
      status: "CANCELLED",
      finishedAt: new Date(),
      progress: {
        phase: "cancelled",
        percent: 100,
        message: "Importación cancelada.",
      },
    });
  }
}

export const catalogImportService = new CatalogImportService();
